version: '3.8'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    command: yarn start:dev
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - '8080:3000'

  postgres:
    image: postgres:12.5
    ports:
      - '35000:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '80:80'
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 0
    restart: unless-stopped
